### ISSUE TITLE
Slow fetching of lyrics

### ISSUE THREAD

**Issue by Verssgn** [cvzi/Youtube-Music-Genius-Lyrics-userscript#18]
It takes around 1-2 minutes for the lyrics to get fetched, is this normal?

**Comment by cvzi** [comment]
No, not normal, it shouldn't take more than a few seconds.

Could you check if it also happens on Youtube.com (not Youtube music) with this user-script: https://github.com/cvzi/Youtube-Genius-Lyrics-userscript

The two scripts use the same techniques, so this would narrow down if the problem is specific to Youtube Music or not.

**Comment by Verssgn** [comment]
Sorry,
I removed all of the installed userscripts and re-tested it and now it runs way faster (Around 30 seconds) so the issue was on my side. 
Thanks for the reply and for making a great script. and sorry for wasting your time.

**Comment by cvzi** [comment]
Which browser do you use?

**Comment by Verssgn** [comment]
I tested it and now the time is down from 30 seconds to 6 so a huge improvement! Thank you!
